from .codebase_is_modified_according_to_git import codebase_is_modified_according_to_git
from .debugger_connected import debugger_connected, run_through_pycharm
from .globalrandomseed import GlobalRandomSeed
from .save_pip_freeze import save_pip_freeze_to_file
from .wait_for_gpu import wait_for_gpu
from .copy_this_file_to_directory import copy_this_file_to_directory
from .tmpfile import get_package_dir, get_tmp_file_dir, cleanup_tmp_dir
from .reduce_dataset_size_to_n_elements import reduce_dataset_size_to_n_elements
from .limit_resources import limit_resources
